### ISSUE TITLE
Swipe Cards: Performing really slow on Galaxy S4

### ISSUE THREAD

**Issue by rvanbaalen** [trendicity/trendicity#24]
On my iPhone 6, the animation runs fairly smooth but on a Galaxy S4 running Android 4.4.2, the performance is horrible. I barely see any animation.

I believe this is caused by the high amount of images being loaded into the view simultaneously. Perhaps we could load +/- 5 images as a stack and add a new one every time someone swiped away another card.

Another note; on both my iPhone 6, a Galaxy S3 mini and a Galaxy S4 I don't see any images initially until I swipe around on some whitespace. At least, that's what it looks like. It could also be that the images are just loading very slow and it just seems like there is no initial image until I start swiping.

**Comment by keithdmoore** [comment]
FYI...If you are not logged in and swipe/drag a card left, you are no longer required to be logged in.

**Comment by rvanbaalen** [comment]
Sweet. That is a huge improvement. I never log in ;-)

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by keithdmoore** [comment]
Not really correct in my opinion but considering what this project is for....it makes sense.

**Comment by rvanbaalen** [comment]
This is done?
