### ISSUE TITLE
Replace <header> for <ion-header-bar> in sidemenu template

### ISSUE THREAD

**Issue by rvanbaalen** [trendicity/trendicity#28]
Especially for the sake of 'showing Ionics UI elements' why should we use `<header>` instead of `<ion-header-bar>` ?

I'm about the replace <header> for <ion-header-bar>. Any objections?

**Comment by rvanbaalen** [comment]
Should still do this and test it.

**Comment by keithdmoore** [comment]
With beta14 upgrade, this was addressed.
