### ISSUE TITLE
Do we have Android users on the team?

### ISSUE THREAD

**Issue by rvanbaalen** [trendicity/trendicity#29]
Is anyone on the team an Android user or do most of you have an iPhone?

I was wondering if 'tap to scroll' is an iOS specific feature or do Android apps offer it as well?

With 'tap to scroll' I mean tapping the header / statusbar to scroll the app's content back to the top.

**Comment by keithdmoore** [comment]
I have an iPhone 5 that I use regularly.  I also have a Samsung Galaxy Tab 3 (10 inch) tablet that I use for testing mobile apps with.  It is running 4.4.2.  The "Tap to scroll" does work in Trendicity on my Android tablet.  Not sure about other apps.

**Comment by thoughtpalette** [comment]
iPhone 6 here

**Comment by antonshevchenko** [comment]
^ same
