### ISSUE TITLE
execvp(): No such file or directory

### ISSUE THREAD

**Issue by rvanbaalen** [trendicity/trendicity#31]
@antonshevchenko I keep getting this error when I run `ionic serve`

Yes, I did run `npm install` first.

**Comment by antonshevchenko** [comment]
@rvanbaalen I've cloned a fresh copy of the repo and switched to beta14 branch and did not get this error. Can you post a screenshot of what happens in the console?

**Comment by rvanbaalen** [comment]
This is the error:

![screen shot 2015-01-16 at 09 57 19](https://cloud.githubusercontent.com/assets/220637/5777115/1e3a38c6-9d66-11e4-97d9-fb454436da91.png)

Due to this error, the server closes. So initially I can open the first page of the app but due to the server being killed with this error, the proxy etc. don't work and I can't refresh anything of course. It's just loaded in memory so to say.

**Comment by rvanbaalen** [comment]
I'll go ahead and kill everything I have locally and re-clone the repo to check if that helps

**Comment by antonshevchenko** [comment]
@rvanbaalen Alright. Let me know how it goes!

**Comment by keithdmoore** [comment]
It could be your version of the ionic cli

**Comment by rvanbaalen** [comment]
Yesterday when we talked about it I updated to the latest version with npm update -g ionic

What version do you run Anton?

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by antonshevchenko** [comment]
@rvanbaalen 1.3.2. Is it still causing problems?

@keithdmoore Do you have the same error when you try running on beta14 branch?

**Comment by keithdmoore** [comment]
I am using 1.3.2.  I blew away my project and started from scratch.  When I ran ionic serve, the server started up and then closed without an error.   The app loaded up in Chrome and the address bar was flashing like it was in an infinite loop.  I was unable to open the javascript console to see what was happening.

**Comment by rvanbaalen** [comment]
I experienced that as well Keith. But after closing Chrome and rerunning ionic serve that issue went away and this issue discussed above showed up. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by antonshevchenko** [comment]
@rvanbaalen Try this: `$ ionic serve [http-port] [livereload-port]` to run using a different port than the usual. See http://forum.ionicframework.com/t/why-ionic-serve-fails/4466/3

**Comment by keithdmoore** [comment]
ionic serve 8081 --noliverelead   no workie...infinite loop

**Comment by keithdmoore** [comment]
I think it might have something to do with either the version of one of the below:
I borrowed mac with these versions,  the app launched just fine:
^C~/projects/github/trendicity $ node --version
v0.10.33
~/projects/github/trendicity $ npm --version
2.1.10
~/projects/github/trendicity $ ionic --version
1.2.9
~/projects/github/trendicity $ gulp --version
[gulp] CLI version 3.6.2
[gulp] Local version 3.8.10

**Comment by keithdmoore** [comment]
@diegonetto will love this!
Problem solved.  Upon obtaining the versions of the above on my macbook pro, I found that gulp wasn't installed.  Gee, it would have been nice to have an error message stating as such.

npm install gulp -g

**Comment by antonshevchenko** [comment]
@keithdmoore Nice! I've added a preinstall script to the `package.json` to make sure users have everything they need, including cordova, ionic and gulp. See 9e67dc36a95fe7815ab97829d8928a0ab46fe5f0.

**Comment by rvanbaalen** [comment]
I love that brilliant mind of yours @keithdmoore :+1: :stuck_out_tongue_closed_eyes: 

Running `npm install` with the current project (that Anton updated with install -g ionic cordova gulp) worked for me. Now that I have gulp up and running, it's all good in the hood. 

This issue is fixed.
