### ISSUE TITLE
Add application icon

### ISSUE THREAD

**Issue by rvanbaalen** [trendicity/trendicity#32]
And perhaps corresponding splashscreen?

This is the file that is being used for this repo now:
![iconpsd](https://cloud.githubusercontent.com/assets/220637/5777253/fe7ad792-9d66-11e4-8645-bd0bf3e0b7dc.png)

(Download the 'not available' image and rename to `.PSD`)

**Comment by antonshevchenko** [comment]
See 768fed1ebc4a46e1c9a4a168224f129a18fcf9f9. Added icon to /resources directory to work with `$ ionic resources`.

**Comment by antonshevchenko** [comment]
Also added splashscreen (see 573aee5b99fb27323699f2a3b5cebb40f1d315d3).

**Comment by troymott** [comment]
Anton, would you like to have Max take a look? He just asked me if there is anything he can do to help.

--Troy

**Comment by antonshevchenko** [comment]
@rvanbaalen Did you push your fix for the resources (icon size)?

**Comment by rvanbaalen** [comment]
@antonshevchenko The issue with the app icon was that you forgot to rename it to PSD instead of PNG.

I just named it as a .png in order for Github to allow the upload of this PSD file :package:
