### ISSUE TITLE
Hooks not working

### ISSUE THREAD

**Issue by antonshevchenko** [trendicity/trendicity#33]
Ported the hooks we had from master and they aren't working (not adding cordova plugins for example).

**Comment by rvanbaalen** [comment]
Ah my bad didn't look further than the issue I encountered. Now I see the root cause of my two issues.

**Comment by rvanbaalen** [comment]
The question we must ask ourselves is: do we still need the hooks? It seems like the ionic cli takes care of most of this logic these days.

What do you think @antonshevchenko @keithdmoore @diegonetto ?

**Comment by antonshevchenko** [comment]
@rvanbaalen We only kept the hooks pertaining to managing cordova plugins, which as far as I know isn't handled by Ionic's CLI.

**Comment by rvanbaalen** [comment]
I noticed that @antonshevchenko 

What is the error you get by the way? For me it seems like a permissions problem

**Comment by keithdmoore** [comment]
I am not having any issues with the plugins

**Comment by antonshevchenko** [comment]
@rvanbaalen After running `ionic platform add ios`, it says in the console that it ran the `after_platform_add` scripts but in reality no plugins are being installed (checked using `cordova plugins list`). I had to manually add them one by one.

**Comment by rvanbaalen** [comment]
Where are we on this one?
