### ISSUE TITLE
CDVPlugin class IonicKeyboard (pluginName: Keyboard) does not exist

### ISSUE THREAD

**Issue by rvanbaalen** [trendicity/trendicity#34]
I just gonna leave this here for now. Should be an easy fix for anyone wanting to hop on. @thoughtpalette perhaps?

When running the `beta14` branch on iOS platform:

```
CDVPlugin class IonicKeyboard (pluginName: Keyboard) does not exist.
2015-01-18 22:32:17.359 trendicity[24209:8844253] ERROR: Plugin 'Keyboard' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
```

**Comment by thoughtpalette** [comment]
I'm not available tonight. I was unaware of tomorrows timeline until today :\

**Comment by antonshevchenko** [comment]
Related to #33.

**Comment by rvanbaalen** [comment]
Where are we on this one?
