### ISSUE TITLE
Search Icon showing up when Favorites link is clicked

### ISSUE THREAD

**Issue by keithdmoore** [trendicity/trendicity#36]

**Comment by keithdmoore** [comment]
Use the "beta14" branch please.

**Comment by keithdmoore** [comment]
@antonshevchenko  Now the search icon doesn't display on the card and list views.

**Comment by antonshevchenko** [comment]
@keithdmoore So you want it to be hidden on map view only?

**Comment by keithdmoore** [comment]
I am fixing it.  Yes, I suppose that would be fine.  The original problem was that the tabs were inoperable when coming from a favorite.  Another issue was the search icon selections werent working as well.  That was the problems found a few months ago.  Chris decided to just remove the search icon upon selecting a favorite.  Ideally, having the search icon and the tabs work properly when coming from a favorite would be desired.  I am putting in my short term fix.

**Comment by thoughtpalette** [comment]
I believe we hid it because at that point the search was context specific and didn't make sense in relation to the favorite view.

**Comment by keithdmoore** [comment]
It makes sense to me to allow the user to decide to search using the search criteria which would then ignore the favorite at that point.

**Comment by keithdmoore** [comment]
@thoughtpalette  Glad to see that you are still alive!

**Comment by keithdmoore** [comment]
Ooops.  My change was in Robin's new map branch.   Anton, my change is the same as yours.  I just put in the beta14-new-map branch.

**Comment by thoughtpalette** [comment]
I'm still here @keithdmoore! Just super busy and away from home.

Here's the reasoning behind the search being disabled. 
https://github.com/trendicity/trendicity/issues/13#issuecomment-64302831

**Comment by keithdmoore** [comment]
I really think it makes sense for the search icon to always be there.  It should wipe out the favorite and do the search.

**Comment by rvanbaalen** [comment]
Noooo dont you dare touch my branch :P

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by rvanbaalen** [comment]
I agree with you keith. But at the same time we should focus on fixing bugs and improving performance instead of fine tuning app use. 

No one will probably use the app. Its just a tech demo. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by keithdmoore** [comment]
In my opinion, it is a bug

**Comment by rvanbaalen** [comment]
Where are we on this one?

**Comment by thoughtpalette** [comment]
@rvanbaalen I believe @antonshevchenko may have taken care of this awhile ago.

**Comment by rvanbaalen** [comment]
@antonshevchenko So what's the status with this one?

cc'ing @keithdmoore since he has been recently active in the repo

**Comment by antonshevchenko** [comment]
@rvanbaalen I pushed a tentative fix. It required to change a bit of the logic behind how we handle favorites. With the fix it now works as @keithdmoore wanted. There is one thing though: the posts are being reloaded on each state change inside the home view. Would be great to avoid this.

**Comment by rvanbaalen** [comment]
Is that new since I refactored the Home controller or was it there before?
I've refactored the Home controller to be compatible with the new maps
logic. Can you confirm the posts are still being updated every state
refresh?

------------------------------------------
Neverwoods
Margrietlaan 10
Willemstad, Curaçao
T (+599 9) 522 9996
W http://www.neverwoods.com

"we create the future"

**Comment by antonshevchenko** [comment]
The thing is the posts are out of sync between the different tabs.

**Comment by antonshevchenko** [comment]
@keithdmoore Did you manage to fix the issue with posts being out of sync between views? I'm still trying to figure it out.

**Comment by rvanbaalen** [comment]
Take a good look at the home controller. I put some facy stuff in there that might be related. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by keithdmoore** [comment]
Fixed 

Pecked out from my iPhone

**Comment by keithdmoore** [comment]
@antonshevchenko I was going to close the issue but I wanted to ask you to test it out to make sure I didn't miss something.

**Comment by antonshevchenko** [comment]
@keithdmoore Sure thing! I'll check it out right now.

**Comment by antonshevchenko** [comment]
The posts still are out of sync between the card and list tabs.

**Comment by keithdmoore** [comment]
Ok.  I will take a look at it tonight.  I was trying to avoid a refresh when switching between views.

**Comment by antonshevchenko** [comment]
Printing the list of posts (`$scope.posts.data`) gives the same thing for both tabs, but for some reason the first card in the card view is not the first post.

**Comment by keithdmoore** [comment]
I wonder if it is in reverse order?  I dont recall

**Comment by keithdmoore** [comment]
Sometimes the posts are in reverse order.  Not sure how that happens.  However, I did fix the issue with the posts not being the same in the usecase.

Goto Favorites -> Select a favorite -> Select Home from menu.  In this case the posts should be for the current location.  The favorite was not being cleared in this scenario.  With my commit 605612ada95b292d2cb209b099a48e5f6d86079f , It is cleared now.

**Comment by keithdmoore** [comment]
@antonshevchenko can you please retest?

**Comment by antonshevchenko** [comment]
I've retested and the posts are still out of sync. Also selecting a favourite, and then going back home the card view contains the same posts (favorites posts).

**Comment by keithdmoore** [comment]
I noticed the posts are in reverse order sometimes.  Can you give me steps to reproduce?

**Comment by keithdmoore** [comment]
You did get the latest right?

**Comment by antonshevchenko** [comment]
Yes. I just followed your steps for the favorites testing. For the out of sync, it can be noticed when changing the search value (e.g.: from nearby to trending) and viewing the posts on the card and list view tabs.

**Comment by keithdmoore** [comment]
You are testing in Chrome, right?

**Comment by antonshevchenko** [comment]
Tested in both Chrome and Safari

**Comment by keithdmoore** [comment]
I will take another look tonight

**Comment by rvanbaalen** [comment]
Throw me a line on Hangouts tonight. I might have some time to help out and or test.

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by keithdmoore** [comment]
@rvanbaalen fix the map!

**Comment by antonshevchenko** [comment]
@keithdmoore Do you think storing the posts in its own service would make more sense and avoid any weird bugs? Instead of having to inherit the data from `HomeCtrl`.

**Comment by rvanbaalen** [comment]
It does make sense. You could abuse the MapService for this since its already keeping track of posts sort of. All markers have full post data on them. 

Or better yet have a PostsService to share data across controllers and services and use that posts service in the MapService as well (I could do that)

Regarding the map: I have no clue where to get started on this slow-ass loading. From the little debugging I have done so far it just seems like its a slow server response. But that cant be it I figure..

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by keithdmoore** [comment]
Even if its in a service, it going to have to be put on the scope.  Not saying it's a bad idea.  Just dont know if it would fix our issue.  Feel free to dive in and change it up.  I just want to avoid loading the posts across view clicks.  Slows the app down and makes for a not so great experience.

**Comment by keithdmoore** [comment]
@rvanbaalen Markers only have posts that have geo data.  need all of the posts not just the ones with geo info

**Comment by keithdmoore** [comment]
After looking at this further and a discussion with @diegonetto, I am going to create a PostsService

**Comment by keithdmoore** [comment]
@diegonetto I am finished implementing an initial refactoring HomeCtrl to use a PostsService with this commit: https://github.com/trendicity/trendicity/commit/a53a20b07eb6158a43d3f8f72a64a60499ad355f. During this exercise, I found that the map appears to not hang like it did before.  I might have fixed the map issues by doing this.  What a bonus!  I still need to make some more changes to get Favorites to work properly.

**Comment by rvanbaalen** [comment]
Omg thats so cool! Thanks keith! Ill go ahead and pull in the project today. At my office we have multiple mobile test devices and Im about to give them all a spin: Galaxy S3, Galaxy S4, iPhone 4s, iPhone 5 and iPhone 6. These are, at least in this part of the world :wink:, the most used devices atm. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by rvanbaalen** [comment]
I don't wanna spoil all the fun but the map is still slow here (iPhone 6) and loading a favorite location doesn't work. No promises yet but perhaps we could take a look at it together tonight.

**Comment by keithdmoore** [comment]
With all the changes this not a concern any longer.
