### ISSUE TITLE
side menu opens when dragging a card in card view

### ISSUE THREAD

**Issue by keithdmoore** [trendicity/trendicity#37]
Appears to only occur when you have a invoke a url from a ion-tab.  /
Opened an issue: https://github.com/driftyco/ionic/issues/2957

**Comment by antonshevchenko** [comment]
@keithdmoore Check the fix. I tested it out and it works.

**Comment by keithdmoore** [comment]
@antonshevchenko Unfortunately, your fix doesn't work.  One strange thing that happens is that when the changed file, like "cards.js" is reloaded, it works temporarily.  However, if you shut the server down and restart, you soon realize the fix doesn't work.

**Comment by rvanbaalen** [comment]
NEVER restart your server :P

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by antonshevchenko** [comment]
@rvanbaalen Yes! :)

**Comment by keithdmoore** [comment]
I thought I had fixed it several times.

**Comment by antonshevchenko** [comment]
By the way, you forgot to add the `$timeout` dependency in `HomeCtrl` in your fix.

**Comment by keithdmoore** [comment]
Thanks.  I corrected that and changed it back to beforeEnter.  Still doesnt work though.  :-(

**Comment by keithdmoore** [comment]
@diegonetto @alevicki @thoughtpalette any ideas on how to fix this?  any desire to help fix this?  any help would be appreciated.  I am out of ideas on how to fix this.

**Comment by rvanbaalen** [comment]
Is anyone still alive and able to help @keithdmoore out on this?

**Comment by antonshevchenko** [comment]
Been trying to fix it yesterday as well. Tried using a delegate-handle on ion-side-menus with no success.

**Comment by rvanbaalen** [comment]
Troy keeps saying Max wants to help out. This seems like a perfect case where he can help?

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by antonshevchenko** [comment]
And... I tried something crazy right now and it fixed it!

**Comment by antonshevchenko** [comment]
Just noticed, after restarting server it doesn't work again. @rvanbaalen let's get Max's help?

**Comment by rvanbaalen** [comment]
Perhaps inform Troy that he sends out an e-mail requesting help on this
matter.

From what I understood, Keith also had a similar fix before which was gone
after a server restart.

------------------------------------------
Neverwoods
Margrietlaan 10
Willemstad, Curaçao
T (+599 9) 522 9996
W http://www.neverwoods.com

"we create the future"

**Comment by antonshevchenko** [comment]
@rvanbaalen Sent.

**Comment by rvanbaalen** [comment]
:+1:

------------------------------------------
Neverwoods
Margrietlaan 10
Willemstad, Curaçao
T (+599 9) 522 9996
W http://www.neverwoods.com

"we create the future"

**Comment by mhartington** [comment]
Something I noticed that could be the cause. When I added a city to favorites, I was able to pass that ID to the maps view, but not the list view or cards view. Is this something intentional or no?

**Comment by keithdmoore** [comment]
I think that is a separate issue.  Thanks for bringing to our attention.  If you go directly into the app which takes you to the map view.  Then click on card view, you can drag the content and open the menu.  This is what I am trying to correct.

**Comment by keithdmoore** [comment]
@mhartington locally, I removed the favorite id from the href's and removed the routes even.  No luck.  Ran using ````python -m SimpleHTTPServer````  No luck there either.   :-(

**Comment by mhartington** [comment]
This may be a case where there are too many things going on all at once

**Comment by keithdmoore** [comment]
Ok.  I found the problem.   The map integration looks to be the issue.  If I change the default route to the card view; I am not able to drag the content to open the menu.  It works!  Then navigating to the list view, I can drag the content to open the menu.  Navigate back to card view, I am not able to drag the content to open the menu.  Something about displaying the map is causing the issue.  

@mhartington Thanks for your all your help!  Sorry for the fire alarm!

**Comment by keithdmoore** [comment]
I am about to pull out all my hair now!  If I change the default route to the list view, and then navigate to the card view.  The drag on the content opens the side menu.  Arrrgh!

**Comment by keithdmoore** [comment]
Workaround was to do this in the CardViewCtrl:
````javascript
  $scope.$on('$ionicView.enter', function() {
    $ionicHistory.clearHistory();
    $ionicSideMenuDelegate.canDragContent(false);
  });
````

Perry and Mike will work on a more permanent solution.
