### ISSUE TITLE
Write chapter on Getting app ready for production

### ISSUE THREAD

**Issue by keithdmoore** [trendicity/trendicity#41]

**Comment by keithdmoore** [comment]
Minification, obfuscation, etc.

**Comment by rvanbaalen** [comment]
Copy paste this and you're done:

- gulp-minify
- gulp-uglify
- `ionic browser install crosswalk`
- tip & trick: 
  - ionic serve
  - quit server
  - ionic run ios --livereload
  - Now you have browser and ios app with live reloading enabled.

**Comment by keithdmoore** [comment]
discussing workflow using Ionic tooling, specifically with live-reloading both web & simulator apps, icons and splash screens, cordova project best practices, plugin management, and crosswalk.

**Comment by keithdmoore** [comment]
@diegonetto  Looks like this will be a slow process
https://github.com/driftyco/ionic-cli/issues/168

**Comment by rvanbaalen** [comment]
Whats the status on this one? Deprecated right?

**Comment by keithdmoore** [comment]
Yep!
