### ISSUE TITLE
Post markers should close the current popup when selected

### ISSUE THREAD

**Issue by keithdmoore** [trendicity/trendicity#47]

**Comment by rvanbaalen** [comment]
Related issue: https://github.com/angular-ui/angular-google-maps/issues/434

------------------------------------------
Neverwoods
Margrietlaan 10
Willemstad, Curaçao
T (+599 9) 522 9996
W http://www.neverwoods.com

"we create the future"

**Comment by diegonetto** [comment]
Modified the behavior so this is no longer an issue.
