### ISSUE TITLE
Tabs show up at the top on Android devices

### ISSUE THREAD

**Issue by keithdmoore** [trendicity/trendicity#49]

**Comment by rvanbaalen** [comment]
Thats by Ionics design?

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by keithdmoore** [comment]
Yes.  They seem to be setting defaults based on iOS versus Android.   

http://ionicframework.com/docs/api/provider/%24ionicConfigProvider/

**Comment by rvanbaalen** [comment]
Its stupid. I'd prefer same design on both platforms instead of ajusting design to platform standards. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by keithdmoore** [comment]
That would be my preference too.  I like the idea of the same look and feel across platforms.
