### ISSUE TITLE
Map Popup image design

### ISSUE THREAD

**Issue by diegonetto** [trendicity/trendicity#53]
Should we style this or change it to using a Modal instead?

**Comment by rvanbaalen** [comment]
I think the current size is cool but it might help to throw in an animation or so. To open it smoother. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by keithdmoore** [comment]
Can we close this ?

**Comment by rvanbaalen** [comment]
Yes we can.
