### ISSUE TITLE
ListView Action Sheet "Favorite Post's Location"

### ISSUE THREAD

**Issue by diegonetto** [trendicity/trendicity#56]
This functionality has yet to be implemented.

**Comment by rvanbaalen** [comment]
What do you mean exactly? I get 'list view' and 'action sheet' but what's your idea with this

**Comment by antonshevchenko** [comment]
@diegonetto This is already implemented. If a post has a location, by holding down on the image an action sheet will open up with the "Favorite" option.

**Comment by keithdmoore** [comment]
I just tried it for a post with a location and it did not add the location to Favorites

**Comment by antonshevchenko** [comment]
I'll check it out today

**Comment by antonshevchenko** [comment]
Created a PR for this.
