### ISSUE TITLE
Code Quality

### ISSUE THREAD

**Issue by diegonetto** [trendicity/trendicity#57]
Some standardization across how we're handling Dependency Injection across all components, as well as the use of `this` in controllers versus `$scope` needs to be addressed.

**Comment by keithdmoore** [comment]
Which are you suggesting is better?  Using "this" or using $scope ?

**Comment by rvanbaalen** [comment]
From my perspective, using the `controller as` syntax in combination with using `this.` notation in the controller is best practise these days.

**Comment by keithdmoore** [comment]
@diegonetto can you elaborate on this?

**Comment by diegonetto** [comment]
Honestly, I personally think saving a reference to `this`, then having to `angular.bind()` the current context for `$scope.$watch()` functions to work on controller variables adds more lines of code and can be confusing for newcomers because of [prototypal inheritance](https://github.com/angular/angular.js/wiki/Understanding-Scopes#javascript-prototypal-inheritance).

That being said, the `controller as` syntax does aid in reading markup when there are multiple controllers being used in a single view. Since this is not the case in our application, and since this is really a matter of preference, I'd advise against doing it this way, unless we make certain to adequately cover the differences in our book.

This is a great reference link to published best practices - https://github.com/angular/angular.js/wiki/Best-Practices

**Comment by rvanbaalen** [comment]
$scope notation it is. 

Not sure if its related but I always thought that binding verything to $scope also had an performance impace over controller as syntax. 

And since Angular 1.3 they do recommend controller as syntax, right? But as you said we would have to cover that shortly in the book. And most of the code is bound to $scope already so that doesnt take much refactoring. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by keithdmoore** [comment]
I am about to commit some home.js changes to use $scope and some misc cleanup

**Comment by rvanbaalen** [comment]
Great!

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by keithdmoore** [comment]
@rvanbaalen Can you resolve the jshint errors for these ?
controllers/intro.js
controllers/map.js
services/geolocation.js

@antonshevchenko  Can you resolve the jshint errors for these ?
controllers/list.js
directives/on-dbl-tap.js

I will take the rest
