### ISSUE TITLE
Any Questions? slide of intro wizard is incomplete

### ISSUE THREAD

**Issue by diegonetto** [trendicity/trendicity#58]
We should add a link to our marketing site, our names, link to the repo, and any other information we think would make sense to be displayed here.

**Comment by keithdmoore** [comment]
@diegonetto Are you talking about hybridcollective.org ?  Is that the name we should register ?  Any body else have any thoughts on this ?  

I think Troy reserved trendicity.com.

**Comment by keithdmoore** [comment]
Troy reserved trendicity.io  I think this should be used for the marketing url for the app itself.

**Comment by keithdmoore** [comment]
Closed by 20bfc3aae2cd8afd44015d1bf83cbbae397d8c1d

**Comment by troymott** [comment]
Thanks, it is actually trendicity.co.

We will get that going.

--Troy
