### ISSUE TITLE
Intro navigation buttons flicker on slide change

### ISSUE THREAD

**Issue by rvanbaalen** [trendicity/trendicity#63]
For a short period of time, both buttons show in the header bar.

**Comment by keithdmoore** [comment]
I just noticed this too a few minutes ago

**Comment by rvanbaalen** [comment]
When on the last (third) slide and clicking back, the next button shows 'Explore' instead of 'Back' on the second slide

**Comment by rvanbaalen** [comment]
Overlooked a better way to fix this problem by simply adding 

```css
.ng-hide {
    display: none;
}
```

Though that Ionic already incorporated that in their CSS when I tested if `ng-hide` would fix this. @diegonetto noted that they didn't. Therefore we're getting rid of the ugly switch statement and back to multiple buttons, the right way.

**Comment by rvanbaalen** [comment]
Sorry, too eager to commit. Let me test this first.

**Comment by rvanbaalen** [comment]
Aaaand we're ready for retest

**Comment by rvanbaalen** [comment]
@keithdmoore @antonshevchenko @diegonetto @alevicki 

Is the flickering button bug fixed?

**Comment by antonshevchenko** [comment]
@rvanbaalen Works great!
