### ISSUE TITLE
Ionicons dependency and ios7 prefixes

### ISSUE THREAD

**Issue by rvanbaalen** [trendicity/trendicity#64]
Which Ionicons dependency do we use and shouldn't we get rid of the `-ios7-` prefix in favour of `-ios-`?

In bower I see `"ionicons": "~2.0.1"` as a dependency but when I check I only see the ionicons dependency from the `ionic` library being used, which is version `1.*` and still has the `-ios7-` prefixes in there.

**Comment by rvanbaalen** [comment]
I believe this is also one of the notes by our reviewers.

**Comment by antonshevchenko** [comment]
I'm pretty sure I switched the icons to the new ones. We include all new ionicons in Sass.

**Comment by rvanbaalen** [comment]
Wauw. I was probably smoking. This is not an issue at all.
