### ISSUE TITLE
What to do with all the console.logs

### ISSUE THREAD

**Issue by rvanbaalen** [trendicity/trendicity#65]
There are **lots** of `console.log` calls in the app. What do we do with them?

I sometimes even spot code of which it's sole purpose is eventually calling `console.log` like for example this little gem:

```js
  // Handle the login confirmed event raised by the authService
  $scope.$on('event:auth-loginConfirmed', function() {
    console.log('handling event:auth-loginConfirmed...');
  });
```

What do we do with that? I feel like it shouldn't be in the source if it doesn't have a purpose beside 'placeholder' logging.

**Comment by keithdmoore** [comment]
That particular one is for demonstration purposes

**Comment by rvanbaalen** [comment]
And all others? There are *lots* of `console.log`'s

------------------------------------------
Neverwoods
Margrietlaan 10
Willemstad, Curaçao
T (+599 9) 522 9996
W http://www.neverwoods.com

"we create the future"

**Comment by keithdmoore** [comment]
Mostly to let the developer know what is going on in general.

**Comment by rvanbaalen** [comment]
I know what a `console.log` in general does :wink:

What I meant to say is: should it be there? We're publishing the app to the
App Stores; will they allow `console.log`'s? I'm not sure if it's the way
to go but for example when I write about a feature that we didn't use in
Trendicity, I just add that to my writing like 'you can also do this *code
example* but we havent done that in Trendicity'.

Just checking here. This should be part of the tech editing but since
editing and tech editing isn't really done so far, we should consider
straightening out the code ourselves.

We could also replace the console.logs just with inline comments

```js
console.log('This is a fancy feature that does stuff');
```

to

```js
// This is a fancy feature that does stuff
```

That way, it's definitely descriptive to any dev reading the code and
doesn't look like we forgot to implement something (that's a personal
opinion).
I think most dev's will be looking at the source code to see what's
happening instead of checking the log when running the app.


------------------------------------------
Neverwoods
Margrietlaan 10
Willemstad, Curaçao
T (+599 9) 522 9996
W http://www.neverwoods.com

"we create the future"

**Comment by rvanbaalen** [comment]
Shouldn't be adding issues late at night.. this is apparently another non-issue :wink:

We've discussed this topic on Google Hangouts and concluded that `console.logs` aren't that bad after all.

**Comment by rvanbaalen** [comment]
Unused code blocks will be removed.
