### ISSUE TITLE
No Instagram posts when accessed via "Ionic View"

### ISSUE THREAD

**Issue by gulench** [trendicity/trendicity#66]
Instagram posts come up while running the app in the browser. But if you upload the application and view it via "Ionic View", the Instagram posts do not appear, be it on the map, card or list views.

**Comment by rvanbaalen** [comment]
That could be related to the use of a proxy. Can you confirm this is still an issue if you install the app like we describe in the book, by running `ionic run ios` or `ionic run android` or `emulate` instead of `run` for that matter.

**Comment by gulench** [comment]
It seems `ionic.Platform.isWebView()` returns `false` while running inside Ionic View.

Inside `instagram.js`, changing the following line
```javascript
var API_ENDPOINT = ionic.Platform.isWebView() ? 'https://api.instagram.com/v1' : '/instagram/api';
```
to
```javascript
var API_ENDPOINT = 'https://api.instagram.com/v1';
```
did the trick!
