### ISSUE TITLE
Instagram 

### ISSUE THREAD

**Issue by jakblak** [trendicity/trendicity#67]
Hi, I can't seem to get my photos to display. I'm able to login via the browser but it returns a 404 whenever the images are called on map, list or card.  I was able to upload the app via Ionic View and display on my iPhone6.  But when trying to login I received an Error page.  I also tried with using my own Client ID but received same issues.

**Comment by keithdmoore** [comment]
Can you login to Instagram by going to http://instagram.com ?

**Comment by jakblak** [comment]
Yes, when I'm logged in it does show me as being logged into the app and that the app is authorized.  But I get a 404 in my console. 
![img](https://cloud.githubusercontent.com/assets/5496929/7103753/1321516a-e06c-11e4-9b91-421738ea8a47.png)

**Comment by keithdmoore** [comment]
Are you using ionic serve command?

**Comment by keithdmoore** [comment]
Also, make sure u run: 'npm install'

**Comment by jakblak** [comment]
yes, npm installed the node_modules and running ionic serve with rest of app running fine.  Here is another screenshot, it looks like its not GETing media from the passed in geolocation.
![img](https://cloud.githubusercontent.com/assets/5496929/7103955/69bf7fc0-e075-11e4-8d18-25156c8a340c.png)

**Comment by keithdmoore** [comment]
Ok.  I see.  That makes sense.  If no posts are found for a location then a 404 is returned.  What happens when you goto the card or list view and tap the magnifying glass and tap Trending?

**Comment by jakblak** [comment]
So I got it to work!  For some reason on the Node terminal the Proxy Added: /instagram/api
wasn't geting called.  I happened to start it on my windows terminal and now the app is displaying the images.   

Log in doesn't work using Ionic View but I might get and test on Android, thanks for the help.

**Comment by keithdmoore** [comment]
Glad you got it to work.  You will need to use the real api endpoint to run the app in Ionic View.
