### ISSUE TITLE
Available on the App Store link not working

### ISSUE THREAD

**Issue by dgtman** [trendicity/trendicity#68]
The "Available on App Store" link to the iPhone app doesn't work on your website
http://www.trendicity.co/

For that matter, I can't find it in the Apple app store when I search directly.  I'd really like to see that an Ionic app can make it past Apple's super strict review process.

**Comment by keithdmoore** [comment]
There are Ionic apps in the app store.  It is just a rather lengthy process for any app, period.  We hope to have it out there soon.  Hopefully by the middle of next week, it will be out there.

**Comment by dgtman** [comment]
The instructions on Ionic's website are a little light in terms of explaining the process of deploying to the Apple App Store (the Android instructions are a bit more robust).  It would be great if there were some detailed instructions on the Apple App Store deployment process. 

Given how strict Apple tends to be, it would be great if there was a list of "gotchas" (or dos and don't) for keeping Apple happy and approving your app.  I know anecdotally from other developers that the fact that it's a Cordova app is already one strike against it (stupid Apple).

Is this something your book goes into specifically?  

BTW hats off on the awesome app, I wish I had found that app 2 months ago when I started playing with Ionic as it would have saved me a boat-load of time!

**Comment by keithdmoore** [comment]
Getting into the Apple App store is problematic for even true native apps.  Documentation for the process is difficult because they are constantly changing stuff.  Either Xcode changes or iTunesConnect changes, etc, etc.   The book doesn't address this.  Some issues can be found early on if you deploy to the beta review process.  Like for example, I needed to setup a demo account for them to access some portions of the Trendicity app.  Also, they can be picky about ratings.

**Comment by rvanbaalen** [comment]
The authors of this book combined have released several Ionic based apps to the app stores (both Apple's and Google's) without any problems.

From personal experience I can say that I never had any problems releasing a Cordova app to the stores. 

Thanks for the compliments on the app :+1: hope it helps you.

**Comment by rvanbaalen** [comment]
Its true what Keith said by the way. The process changes so often that its hardly doable for us to explain it in a book. As soon as we would publish it, it would be outdated.

**Comment by ppo** [comment]
Still not available on the App Store?

**Comment by rvanbaalen** [comment]
Apple has changed their policy related to third party content. Were now required to implement a filtering service on our own hosted server to enable users to report any of the instagram posts as inapropriate. 

This requires quite some added work for Trendicity which is not covered in the book. We are working on it though. Just dont hold your breath. 

If you clone the repo and read the book you'll be easily able to install Trendicity on your own phone.

**Comment by ppo** [comment]
Thanks for the quick answer. I'll do that. It was to that a quick look before buying/reading the book ;-)

**Comment by keithdmoore** [comment]
You can also check out the app in your browser as well.

**Comment by ppo** [comment]
That's also a good idea ;-)

**Comment by keithdmoore** [comment]
App is in the Apple App Store.  Sorry for the delay
