### ISSUE TITLE
/www/js/config.js

### ISSUE THREAD

**Issue by Robinyo** [trendicity/trendicity#71]
Is `/www/js/config.js` used by the app?

N.B. Its not mentioned in the text of the book.

**Comment by keithdmoore** [comment]
No.  We initially used the Yeoman Ionic Generator to create the app.   It needs to be removed.

**Comment by Robinyo** [comment]
Ahh, the generator authored by Diego.

Thanks.

**Comment by keithdmoore** [comment]
Correct.  Some of the early feedback we got was to use gulp instead of grunt so we decided to just use the Ionic gulp base.  Most of the team uses the generator for new projects because it offers quite a few benefits.

**Comment by Robinyo** [comment]
To remove the config module In app.js you just need to:
-  remove the reference to 'config'
- .run(function($rootScope, $ionicPlatform) {  // .run(function($rootScope, $ionicPlatform, ENV)
- // console.log('Environment:', ENV.name);

BTW, it would be good if you could add comments like https://github.com/johnpapa/angular-styleguide#style-y165

angular.module('Trendicity', [

  // see /www/js
  'config',

  // see /www/lib
  'ionic',
  'ionic.contrib.ui.tinderCards',
  'ionic.contrib.icon',
  'LocalStorageModule',
  'ngCordova',
  'http-auth-interceptor',
  'uiGmapgoogle-maps'
])

**Comment by keithdmoore** [comment]
I forgot.   The app is using the ENV hash.
