### ISSUE TITLE
Failed at the trendicity@1.0.0 preinstall script 'npm install -g cordova ionic gulp bower'.

### ISSUE THREAD

**Issue by freeever** [trendicity/trendicity#72]
I checkout the project using git, tried to run "npm install -g cordova ionic gulp bower" in Windows7 command line, the following error happened:

0 info it worked if it ends with ok
1 verbose cli [ 'D:\dev\nodejs\\node.exe',
1 verbose cli   'D:\dev\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose readDependencies loading dependencies from F:\workspace\ionic\trendicity\package.json
5 warn package.json trendicity@1.0.0 No license field.
6 verbose install where, deps [ 'F:\workspace\ionic\trendicity',
6 verbose install   [ 'cordova',
6 verbose install     'gulp',
6 verbose install     'gulp-concat',
6 verbose install     'gulp-minify-css',
6 verbose install     'gulp-rename',
6 verbose install     'gulp-sass',
6 verbose install     'bower',
6 verbose install     'gulp-util',
6 verbose install     'shelljs' ] ]
7 verbose install where, peers [ 'F:\workspace\ionic\trendicity', [] ]
8 verbose installManyTop reading for lifecycle F:\workspace\ionic\trendicity\package.json
9 info preinstall trendicity@1.0.0
10 verbose unsafe-perm in lifecycle true
11 info trendicity@1.0.0 Failed to exec preinstall script
12 verbose stack Error: trendicity@1.0.0 preinstall: `npm install -g cordova ionic gulp bower`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (D:\dev\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
12 verbose stack     at EventEmitter.emit (events.js:110:17)
12 verbose stack     at ChildProcess.<anonymous> (D:\dev\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
12 verbose stack     at ChildProcess.emit (events.js:110:17)
12 verbose stack     at maybeClose (child_process.js:1015:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
13 verbose pkgid trendicity@1.0.0
14 verbose cwd F:\workspace\ionic\trendicity
15 error Windows_NT 6.1.7601
16 error argv "D:\dev\nodejs\\node.exe" "D:\dev\nodejs\node_modules\npm\bin\npm-cli.js" "install"
17 error node v0.12.4
18 error npm  v2.10.1
19 error code ELIFECYCLE
20 error trendicity@1.0.0 preinstall: `npm install -g cordova ionic gulp bower`
20 error Exit status 1
21 error Failed at the trendicity@1.0.0 preinstall script 'npm install -g cordova ionic gulp bower'.
21 error This is most likely a problem with the trendicity package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm install -g cordova ionic gulp bower
21 error You can get their info via:
21 error     npm owner ls trendicity
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

**Comment by keithdmoore** [comment]
I don't have a windows environment to test this on.  My apologies, I am not sure what the problem is.

**Comment by keithdmoore** [comment]
I did notice there are references to  "D:" and "F:"  That maybe be the source of your problem.  Maybe node is installed on the "D" drive and your are executing this on your "F:" drive, perhaps.

**Comment by freeever** [comment]
Thanks for your quick reply. I believe it is OK that the NodeJS and Project are on different drive. I thought it might be caused by missing node-gyp. I will install node-gyp as per instruction at https://github.com/TooTallNate/node-gyp and let you know the result.
Thanks,
Daniel

**Comment by freeever** [comment]
I closed this issue by accident. Could you re-open it? thanks

**Comment by freeever** [comment]
out of date
