### ISSUE TITLE
Problem with npm install

### ISSUE THREAD

**Issue by arthurparahyba** [trendicity/trendicity#73]
I keep getting this error when I run npm install:

npm ERR! 404 Registry returned 404 for GET on http://registry.npmjs.org/trendicity
npm ERR! 404
npm ERR! 404 'trendicity' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Arthur\ionic-projects\trendicity\npm-debug.log

**Comment by keithdmoore** [comment]
Are you sure the current directory is "trendicity" when running npm install?

**Comment by arthurparahyba** [comment]
Yes, i'm sure.

**Comment by keithdmoore** [comment]
And you cloned the project from the repo correct?

**Comment by arthurparahyba** [comment]
I think so.

$ git clone https://github.com/trendicity/trendicity
Cloning into 'trendicity'...
remote: Counting objects: 2683, done.
remote: Total 2683 (delta 0), reused 0 (delta 0), pack-reused 2683
Receiving objects: 100% (2683/2683), 6.55 MiB | 198.00 KiB/s, done.
Resolving deltas: 100% (1715/1715), done.
Checking connectivity... done.

$ cd trendicity/

Arthur@parahyba MINGW64 ~/ionic-projects/trendicity (master)
$ npm install
npm WARN package.json trendicity@1.0.0 No license field.

> trendicity@1.0.0 preinstall C:\Users\Arthur\ionic-projects\trendicity
> npm install -g cordova ionic gulp bower

C:\Users\Arthur\AppData\Roaming\npm\gulp -> C:\Users\Arthur\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
C:\Users\Arthur\AppData\Roaming\npm\bower -> C:\Users\Arthur\AppData\Roaming\npm\node_modules\bower\bin\bower
C:\Users\Arthur\AppData\Roaming\npm\cordova -> C:\Users\Arthur\AppData\Roaming\npm\node_modules\cordova\bin\cordova
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic" "gulp" "bower"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read
...
